### PR TITLE
fix(types): fix type error if nuxtIcon property doesn't exist in appConfig

### PR DESCRIPTION
**Pull request by chris-lsn**
related issue 

https://github.com/nuxt-modules/icon/issues/62

### CODE REVIEW

**Comment by ennioVisco** [comment]
Well, this is not exactly a chore. This bug currently breaks builds when strict type-checking is enabled!

**Comment by ineshbose** [comment]
Is `types.d.ts` necessary? Nuxt already generates that I believe for all modules accordingly into the `.nuxt` directory.

**Comment by ennioVisco** [comment]
> Is `types.d.ts` necessary? Nuxt already generates that I believe for all modules accordingly into the `.nuxt` directory.
> 
> I do see the intention is to extend `AppConfig`

Perhaps it should be tracked as a nuxt issue. Tbh I'd say having them autogenerated is kind of an anti-pattern. 
What happens if two modules define the same config?

**Comment by Atinux** [comment]
> Tbh I'd say having them autogenerated is kind of an anti-pattern.
Why is that?

> What happens if two modules define the same config?
It can happen but in 5 years using Nuxt with modules, never happened

**Comment by ennioVisco** [comment]
> > Tbh I'd say having them autogenerated is kind of an anti-pattern.
>
>  Why is that?

Well, I'd expect modules to explicitly declare the interfaces, so that evolutions of the modules interface are explicitly handled by rigorous type-checking from the module authors, and not found out by users accidentally when updating.

> > What happens if two modules define the same config?
>
>  It can happen but in 5 years using Nuxt with modules, never happened

That said, if these cases are very infrequent/never happened, then perhaps it's reasonable to ignore them.

**Comment by chris-lsn** [comment]
> Is `types.d.ts` necessary? Nuxt already generates that I believe for all modules accordingly into the `.nuxt` directory.
> 
> I do see the intention is to extend `AppConfig` (but that is handled by `nuxt-module-builder`, see https://github.com/nuxt/module-builder/blob/844e8ddf598cf9835c250a77f6452433e3678d49/src/build.ts#L117-L123)

I think it is necessary, nuxt auto import type only if the nuxtIcon option is defined, we could either manually typing app config or force users to add nuxtIcon option in app.config.ts to resolve this issue.

**Comment by ineshbose** [comment]
Thanks for sharing your thoughts. Sorry for asking further, but out of curiosity I'd like to understand as well - is there any module doing this?

I missed out that `NuxtConfig` is different from `AppConfig`, but the repro in #62 doesn't use it from what I see. However, instead of creating `types.d.ts` with all imports from `@nuxt/schema`, do you think it can just be done in `module.ts` like:

```ts
declare module '@nuxt/schema' {
  interface AppConfig {
    nuxtIcon?: ModuleOptions
  }
}
```

Doesn't require any additional imports or exports! See other modules extend NuxtHooks in a similar way like so: https://github.com/nuxt-modules/tailwindcss/blob/05aaa004f5dba3cea4ceb1cd01363b1544af58dc/src/module.ts#L43-L47

**Comment by ineshbose** [comment]
Moreover, the module also uses the `schema:extend` hook (https://nuxt.com/docs/api/advanced/hooks, https://github.com/nuxt-modules/icon/blob/0ae93b806f0633f9ee65599136655c0456ffed95/src/module.ts#L24-L64) to extend app config. If you go to https://stackblitz.com/github/nuxt-modules/icon and then `playground/.nuxt/schema/nuxt.schema.d.ts`, there's the generated interface. (I'm exploring this as well 😄)

**Comment by ineshbose** [comment]
I see the problem being raised in the runtime components in the module after changes in #56, and type configuration depends on execution for the hook so I think your solution is suitable except that I would extend the interface in `module.ts` than `types.d.ts`, and if the hook would be required in place of extending interface as it means maintaining two copies of a code imo! 🙂

**Comment by stafyniaksacha** [comment]
I got same issue,

Found that adding empty object to `app.config.ts` solve the issue:

```ts
export default defineAppConfig({
  nuxtIcon: {},
})
```

**Comment by ennioVisco** [comment]
> I got same issue,
> 
> Found that adding empty object to `app.config.ts` solves it:
> 
> ```ts
> export default defineAppConfig({
>   nuxtIcon: {},
> })
> ```

it seems to only work in dev mode :/

**Comment by frasza** [comment]
@Atinux Any idea on this? Build breaking...

**Comment by frasza** [comment]
@luke-z with that `index.d.ts` snippet you provided I encounter another error:

```bash
node_modules/nuxt-icon/dist/runtime/Icon.vue:28:33 - error TS7053: Element implicitly has an 'any' type because expression of type 'string & {}' can't be used to index type '{}'.

28 const iconName = computed(() => (appConfig.nuxtIcon?.aliases || {})[props.name] || props.name)
```

**Comment by pratik149** [comment]
> @luke-z with that `index.d.ts` snippet you provided I encounter another error:
> 
> ```shell
> node_modules/nuxt-icon/dist/runtime/Icon.vue:28:33 - error TS7053: Element implicitly has an 'any' type because expression of type 'string & {}' can't be used to index type '{}'.
> 
> 28 const iconName = computed(() => (appConfig.nuxtIcon?.aliases || {})[props.name] || props.name)
> ```

I found a temporary workaround and that is to suppress that typescript error, just so as to not break the build.

In your `tsconfig.json` file and in `compilerOptions` object, add this key-pair `"suppressImplicitAnyIndexErrors": true`

This is how my tsconfig.json looks like

```js
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": true,
    "suppressImplicitAnyIndexErrors": true,
    "types": [
      "@vueuse/nuxt",
      "@pinia/nuxt"
    ]
  }
}
```

**Comment by danielgdev** [comment]
Temporarily this works for me.

```typescript
// app.config.ts
export interface NuxtIconModuleOptions {
  size?: string | false
  class?: string
  aliases?: { [alias: string]: string }
}

export default defineAppConfig({
  nuxtIcon: {
    size: '24px', // default <Icon> size applied
    class: 'icon', // default <Icon> class applied
    aliases: {}
  } as NuxtIconModuleOptions
})
```

**Comment by ineshbose** [comment]
Does the issue persist in recently released v0.4.0?

**Comment by Pikatsuto** [comment]
Hello yes I confirm that the bug is still present because I just did the test

**Pull request closed without merging**
